language: groovy

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc

script: ./gradlew clean build

jdk:
  - oraclejdk8
  - openjdk8

env: TERM=dumb

after_success: ./gradlew coveralls
